# Based on https://github.com/containers/toolbox/blob/main/images/fedora/f37/Containerfile
FROM registry.fedoraproject.org/fedora:42

LABEL com.github.containers.toolbox="true" \
      name="fedora-kernel-toolbox" \
      version="42"

RUN rm /etc/rpm/macros.image-language-conf
RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf

RUN dnf -y upgrade
RUN dnf -y swap coreutils-single coreutils-full
RUN dnf -y swap glibc-minimal-langpack glibc-all-langpacks

COPY missing-docs /
RUN dnf -y install $(<missing-docs)
RUN rm /missing-docs

COPY extra-packages /
RUN dnf -y install $(<extra-packages)
RUN rm /extra-packages
